### ISSUE TITLE
AntiDosFirewall Error

### ISSUE THREAD

**Issue by RezaAVS** [VahidN/DNTCommon.Web.Core#10]
# Summary of the issue
InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.

## Error

```

    Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
    Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
    Microsoft.Extensions.Caching.Memory.CacheExtensions.Set<TItem>(IMemoryCache cache, object key, TItem value, DateTimeOffset absoluteExpiration)
    DNTCommon.Web.Core.MemoryCacheService.Add<T>(string cacheKey, T value, DateTimeOffset absoluteExpiration)
    DNTCommon.Web.Core.AntiDosFirewall.IsDosAttack(AntiDosFirewallRequestInfo requestInfo)
    DNTCommon.Web.Core.AntiDosFirewall.ShouldBlockClient(AntiDosFirewallRequestInfo requestInfo)
    DNTCommon.Web.Core.AntiDosMiddleware.Invoke(HttpContext context, IOptionsSnapshot<AntiDosConfig> antiDosConfig, IAntiDosFirewall antiDosFirewall)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

## Detail Error:

```
System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.

   at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)

   at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()

   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value, DateTimeOffset absoluteExpiration)

   at DNTCommon.Web.Core.MemoryCacheService.Add[T](String cacheKey, T value, DateTimeOffset absoluteExpiration)

   at DNTCommon.Web.Core.AntiDosFirewall.IsDosAttack(AntiDosFirewallRequestInfo requestInfo)

   at DNTCommon.Web.Core.AntiDosFirewall.ShouldBlockClient(AntiDosFirewallRequestInfo requestInfo)

   at DNTCommon.Web.Core.AntiDosMiddleware.Invoke(HttpContext context, IOptionsSnapshot`1 antiDosConfig, IAntiDosFirewall antiDosFirewall)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/DNTCommon.Web.Core/commit/5656e66c0a29bd7fe436433e89f280b6017c0428
