### ISSUE TITLE
Using partial view from other assembly

### ISSUE THREAD

**Issue by MarcelVersteeg** [VahidN/DNTCommon.Web.Core#69]
I am using your `ViewRendererService` to render a razor view to a string, using its `RenderViewToStringAsync` method. In this view I have a call to `Html.PartialAsync` with the name of a view that resides in another assembly. However, this results in an `InvalidOperationException` indicating that the view cannot be found. Is it possible? If so, how do I do this.

## Environment

```
DNTCommon.Web.Core version: 6.2.1
.NET Core SDK version: 8
IDE: VS2022 (17.11.3)
```

## Code:
```
                ViewRendererService rendererService = new(viewEngine,
                                                          tempDataProvider,
                                                          serviceProvider,
                                                          httpContextAccessor);
                string response = await rendererService.RenderViewToStringAsync(viewPath,
                                                                                createModelFunction(httpContext)).
                                                        ConfigureAwait(ConfigureAwaitOptions.ContinueOnCapturedContext);
```

## Output:

```
System.InvalidOperationException: The partial view '~/Shared/Pages/Shared/_SharedView.cshtml' was not found. The following locations were searched:
~/Shared/Pages/Shared/_SharedView.cshtml
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCoreGeneratedDocument.Pages_Famversteeg_InvalidParameter.<ExecuteAsync>b__8_0()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCoreGeneratedDocument.Pages_Famversteeg_InvalidParameter.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at DNTCommon.Web.Core.ViewRendererService.RenderViewToStringAsync[TModel](String viewNameOrPath, TModel model) in D:\a\DNTCommon.Web.Core\DNTCommon.Web.Core\src\DNTCommon.Web.Core\Mvc\ViewRendererService.cs:line 80
   at MyAssembly.Helpers.RazorHelper.RenderView[TModel](String viewPath, Func`2 createModelFunction, IHttpContextAccessor httpContextAccessor, IServiceProvider serviceProvider, IRazorViewEngine viewEngine, ITempDataProvider tempDataProvider) in RazorHelper.cs:line 48
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()```
```

**Comment by VahidN** [comment]
No it's possible.
